#!/usr/bin/env python3
"""Train a leakage-safe event BDT from two jet scores plus event topology.

The test split is never opened.  Training-event jet scores are generated by
event-level cross-fitting by default, while validation scores are generated by
the supplied full per-jet model.  This prevents the stacked event classifier
from learning from in-sample jet-tagger predictions.

Default event inputs (12)
-------------------------
* leading_jet_score, subleading_jet_score;
* event_invariant_mass, n_jets_original;
* leading/subleading jet_energy, jet_pt, jet_p and jet_theta.

The two jets and every jet-level observable are ordered by decreasing energy.
Physical weights can be supplied either in an ``event_weight`` Parquet column
or through a per-process JSON normalization manifest.  The manifest route uses

    weight = sigma_pb * luminosity_ab^-1 * 1e6
             * filter_efficiency * k_factor * branching_fraction / N_generated

where ``N_generated`` is specified separately for train and validation.  If no
physical normalization is available, unit weights are used and significance is
explicitly labelled as an unnormalised proxy.
"""

from __future__ import annotations

import argparse
import fnmatch
import json
import math
import warnings
from dataclasses import dataclass
from pathlib import Path

import joblib
import matplotlib
import numpy as np
import pyarrow as pa
import pyarrow.compute as pc
import pyarrow.parquet as pq
from sklearn.base import clone
from sklearn.ensemble import HistGradientBoostingClassifier
from sklearn.inspection import permutation_importance
from sklearn.metrics import average_precision_score, roc_auc_score, roc_curve
from sklearn.model_selection import StratifiedKFold

matplotlib.use("Agg")
import matplotlib.pyplot as plt


ORDERING_COLUMN = "jet_energy"
SCALAR_TOPOLOGY_COLUMNS = ("event_invariant_mass", "n_jets_original")
PAIR_TOPOLOGY_COLUMNS = ("jet_energy", "jet_pt", "jet_p", "jet_theta")
NUMBER_OF_JETS = 2


@dataclass
class EventData:
    jet_inputs: np.ndarray       # [event, jet, per-jet feature]
    topology: np.ndarray         # [event, topology feature]
    weights: np.ndarray          # expected-yield/event weights
    processes: np.ndarray        # process name for composition/templates
    used_physical_weights: bool
    missing: dict[str, int]
    infinities: dict[str, int]


@dataclass(frozen=True)
class SampleNormalization:
    name: str
    class_name: str
    path_glob: str
    cross_section_pb: float
    generated_events: dict[str, float]
    filter_efficiency: float = 1.0
    k_factor: float = 1.0
    branching_fraction: float = 1.0

    def weight(self, split: str, luminosity_ab_inv: float) -> float:
        if split not in self.generated_events:
            raise ValueError(
                f"Sample {self.name!r} has no generated_events entry for split {split!r}"
            )
        denominator = float(self.generated_events[split])
        if denominator <= 0:
            raise ValueError(
                f"Sample {self.name!r}: generated_events[{split!r}] must be positive"
            )
        # 1 pb * 1 ab^-1 = 10^6 expected events.
        return (self.cross_section_pb * luminosity_ab_inv * 1.0e6
                * self.filter_efficiency * self.k_factor
                * self.branching_fraction / denominator)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Train an event BDT using two jet-tagger scores and topology."
    )
    parser.add_argument("--dataset-root", type=Path,
                        default=Path("cache/analysis_dataset"))
    parser.add_argument("--jet-model", type=Path,
                        default=Path("outputs/ml/per_jet_bdt_6_variables/per_jet_bdt.joblib"))
    parser.add_argument("--output-dir", type=Path,
                        default=Path("outputs/ml/event_bdt_jet_scores_topology"))
    parser.add_argument("--weight-column", default="event_weight",
                        help="Scalar expected-yield weight; unit weights if absent everywhere.")
    parser.add_argument(
        "--normalization-manifest", type=Path,
        help=("JSON manifest containing luminosity, per-process cross sections, and "
              "generated-event counts. Takes precedence over --weight-column."),
    )
    parser.add_argument("--weight-scale", type=float, default=1.0,
                        help="Global factor applied to event weights (e.g. luminosity rescaling).")
    parser.add_argument("--max-training-events-per-class", type=int, default=0)
    parser.add_argument("--max-validation-events-per-class", type=int, default=0)
    parser.add_argument("--batch-size", type=int, default=100_000)
    parser.add_argument("--cross-fit-folds", type=int, default=5,
                        help="Event-level folds for out-of-fold training jet scores; >=2.")
    parser.add_argument(
        "--training-score-mode", choices=("crossfit", "pretrained"),
        default="crossfit",
        help="Use crossfit unless making a deliberately optimistic diagnostic.",
    )
    parser.add_argument("--learning-rate", type=float, default=0.05)
    parser.add_argument("--max-iterations", type=int, default=300)
    parser.add_argument("--max-leaf-nodes", type=int, default=31)
    parser.add_argument("--min-samples-leaf", type=int, default=100)
    parser.add_argument("--l2-regularization", type=float, default=1.0)
    parser.add_argument(
        "--background-systematic", type=float, default=None,
        help="Deprecated single uncertainty; also sets the optimisation uncertainty.",
    )
    parser.add_argument(
        "--background-systematics", type=float, nargs="+",
        default=[0.0, 0.01, 0.05, 0.10],
        help="Fractional background uncertainties reported at the chosen cut.",
    )
    parser.add_argument(
        "--optimize-background-systematic", type=float, default=0.05,
        help="Fractional background uncertainty used to choose the best threshold.",
    )
    parser.add_argument("--scan-points", type=int, default=1001)
    parser.add_argument("--min-background-neff", type=float, default=10.0)
    parser.add_argument("--template-bins", type=int, default=8)
    parser.add_argument("--importance-events", type=int, default=50_000)
    parser.add_argument("--importance-repeats", type=int, default=5)
    parser.add_argument("--n-jobs", type=int, default=1)
    parser.add_argument("--random-state", type=int, default=42)
    return parser.parse_args()


def validate_args(args: argparse.Namespace) -> None:
    if args.batch_size <= 0 or args.scan_points < 10 or args.template_bins < 2:
        raise ValueError("Batch size, scan points and template bins are invalid")
    if args.cross_fit_folds < 2:
        raise ValueError("--cross-fit-folds must be at least 2")
    if args.max_training_events_per_class < 0 or args.max_validation_events_per_class < 0:
        raise ValueError("Event caps must be non-negative")
    if args.weight_scale <= 0:
        raise ValueError("Weight scale must be positive")
    if args.background_systematic is not None:
        if args.background_systematic < 0:
            raise ValueError("Background systematic must be non-negative")
        args.optimize_background_systematic = args.background_systematic
        args.background_systematics = sorted(set(
            [*args.background_systematics, args.background_systematic]
        ))
    if args.optimize_background_systematic < 0 or any(
            value < 0 for value in args.background_systematics):
        raise ValueError("Background systematics must be non-negative")
    if args.optimize_background_systematic not in args.background_systematics:
        args.background_systematics = sorted(set(
            [*args.background_systematics, args.optimize_background_systematic]
        ))


def parquet_files(directory: Path) -> list[Path]:
    files = sorted(directory.rglob("*.parquet"))
    if not files:
        raise FileNotFoundError(f"No Parquet files found under {directory}")
    return files


def validation_directory(class_directory: Path) -> Path:
    for name in ("validation", "val"):
        candidate = class_directory / name
        if candidate.is_dir() and any(candidate.rglob("*.parquet")):
            return candidate
    raise FileNotFoundError(f"No validation/ or val/ split below {class_directory}")


def load_normalization_manifest(path: Path) -> tuple[float, list[SampleNormalization]]:
    payload = json.loads(path.read_text())
    luminosity = float(payload["luminosity_ab_inv"])
    if luminosity <= 0:
        raise ValueError("luminosity_ab_inv must be positive")
    raw_samples = payload.get("samples")
    if not isinstance(raw_samples, list) or not raw_samples:
        raise ValueError("Normalization manifest must contain a non-empty samples list")
    samples: list[SampleNormalization] = []
    names: set[str] = set()
    for raw in raw_samples:
        sample = SampleNormalization(
            name=str(raw["name"]), class_name=str(raw["class"]),
            path_glob=str(raw["path_glob"]),
            cross_section_pb=float(raw["cross_section_pb"]),
            generated_events={str(key): float(value)
                              for key, value in raw["generated_events"].items()},
            filter_efficiency=float(raw.get("filter_efficiency", 1.0)),
            k_factor=float(raw.get("k_factor", 1.0)),
            branching_fraction=float(raw.get("branching_fraction", 1.0)),
        )
        if sample.name in names:
            raise ValueError(f"Duplicate sample name in manifest: {sample.name!r}")
        if sample.class_name not in {"signal", "background"}:
            raise ValueError(f"Sample {sample.name!r}: class must be signal or background")
        factors = (sample.cross_section_pb, sample.filter_efficiency,
                   sample.k_factor, sample.branching_fraction)
        if sample.cross_section_pb <= 0 or any(value < 0 for value in factors[1:]):
            raise ValueError(f"Sample {sample.name!r}: invalid normalization factor")
        names.add(sample.name)
        samples.append(sample)
    return luminosity, samples


def manifest_file_weights(
        files: list[Path], dataset_root: Path, class_name: str, split: str,
        luminosity_ab_inv: float, samples: list[SampleNormalization],
        weight_scale: float) -> dict[Path, tuple[str, float]]:
    assignments: dict[Path, tuple[str, float]] = {}
    for path in files:
        relative = path.relative_to(dataset_root).as_posix()
        matches = [sample for sample in samples
                   if sample.class_name == class_name
                   and fnmatch.fnmatchcase(relative, sample.path_glob)]
        if len(matches) != 1:
            names = [sample.name for sample in matches]
            raise ValueError(
                f"{relative} must match exactly one {class_name} manifest sample; "
                f"matched {names}"
            )
        sample = matches[0]
        assignments[path] = (
            sample.name,
            sample.weight(split, luminosity_ab_inv) * weight_scale,
        )
    matched_names = {name for name, _ in assignments.values()}
    expected_names = {sample.name for sample in samples
                      if sample.class_name == class_name
                      and split in sample.generated_events}
    absent = expected_names - matched_names
    if absent:
        warnings.warn(
            f"Manifest {class_name} sample(s) have no {split} files: {sorted(absent)}"
        )
    return assignments


def inferred_process_name(path: Path, split_root: Path, class_name: str) -> str:
    relative = path.relative_to(split_root)
    if len(relative.parts) > 1:
        return relative.parts[0]
    stem = relative.stem
    return stem.split("_part_", 1)[0] if class_name == "background" else class_name


def is_numeric_scalar(dtype: pa.DataType) -> bool:
    return (pa.types.is_integer(dtype) or pa.types.is_floating(dtype)
            or pa.types.is_decimal(dtype)) and not pa.types.is_boolean(dtype)


def is_numeric_list(dtype: pa.DataType) -> bool:
    return (pa.types.is_list(dtype) or pa.types.is_large_list(dtype)
            or pa.types.is_fixed_size_list(dtype)) and is_numeric_scalar(dtype.value_type)


def weight_availability(files: list[Path], weight_column: str) -> bool:
    present = [weight_column in pq.ParquetFile(path).schema_arrow.names for path in files]
    if any(present) and not all(present):
        missing = [str(path) for path, has_weight in zip(files, present) if not has_weight]
        raise ValueError(
            f"Weight column {weight_column!r} exists in only some shards; missing in "
            f"{len(missing)} shard(s), including {missing[0]}"
        )
    return all(present)


def validate_schema(files: list[Path], jet_features: list[str], use_weights: bool,
                    weight_column: str) -> None:
    pair_columns = set(jet_features) | set(PAIR_TOPOLOGY_COLUMNS) | {ORDERING_COLUMN}
    scalar_columns = set(SCALAR_TOPOLOGY_COLUMNS)
    if use_weights:
        scalar_columns.add(weight_column)
    for path in files:
        schema = pq.ParquetFile(path).schema_arrow
        fields = {field.name: field.type for field in schema}
        missing = (pair_columns | scalar_columns) - fields.keys()
        if missing:
            raise ValueError(f"{path} is missing required columns: {sorted(missing)}")
        for name in pair_columns:
            if not is_numeric_list(fields[name]):
                raise TypeError(f"{path}: {name!r} must be a numeric jet-level list")
        for name in scalar_columns:
            if not is_numeric_scalar(fields[name]):
                raise TypeError(f"{path}: {name!r} must be scalar numeric")


def numeric_array(array: pa.Array) -> np.ndarray:
    converted = pc.cast(array, pa.float32(), safe=False)
    return np.asarray(converted.to_numpy(zero_copy_only=False), dtype=np.float32)


def first_two(array: pa.Array, name: str) -> np.ndarray:
    lengths = pc.list_value_length(array)
    too_short = pc.any(pc.fill_null(pc.less(lengths, NUMBER_OF_JETS), True)).as_py()
    if too_short:
        raise ValueError(f"{name!r} contains an event with fewer than two jets")
    return np.column_stack([
        numeric_array(pc.list_element(array, index)) for index in range(NUMBER_OF_JETS)
    ])


def load_events(files: list[Path], jet_features: list[str], batch_size: int,
                maximum: int, description: str, use_weight_column: bool,
                weight_column: str, weight_scale: float, split_root: Path,
                class_name: str,
                file_weights: dict[Path, tuple[str, float]] | None = None) -> EventData:
    pair_columns = list(dict.fromkeys([*jet_features, *PAIR_TOPOLOGY_COLUMNS,
                                       ORDERING_COLUMN]))
    read_columns = [*SCALAR_TOPOLOGY_COLUMNS, *pair_columns]
    if use_weight_column:
        read_columns.append(weight_column)
    jet_blocks: list[np.ndarray] = []
    topology_blocks: list[np.ndarray] = []
    weight_blocks: list[np.ndarray] = []
    process_blocks: list[np.ndarray] = []
    missing_counts: dict[str, int] = {}
    infinity_counts: dict[str, int] = {}
    loaded = 0
    print(f"\nLoading {description} from {len(files)} shard(s)")
    for file_number, path in enumerate(files, 1):
        parquet = pq.ParquetFile(path)
        for batch in parquet.iter_batches(batch_size=batch_size, columns=read_columns,
                                          use_threads=True):
            arrays = {name: batch.column(batch.schema.get_field_index(name))
                      for name in read_columns}
            pairs = {name: first_two(arrays[name], name) for name in pair_columns}
            energy = pairs[ORDERING_COLUMN]
            swap = (np.isfinite(energy[:, 0]) & np.isfinite(energy[:, 1])
                    & (energy[:, 1] > energy[:, 0]))
            if np.any(swap):
                for values in pairs.values():
                    values[swap] = values[swap, ::-1]
            jets = np.stack([pairs[name] for name in jet_features], axis=2)
            topology_names = [*SCALAR_TOPOLOGY_COLUMNS, *(
                f"{rank}_{name}" for name in PAIR_TOPOLOGY_COLUMNS
                for rank in ("leading", "subleading")
            )]
            topology_values = [numeric_array(arrays[name])
                               for name in SCALAR_TOPOLOGY_COLUMNS]
            topology_values.extend(
                pairs[name][:, index]
                for name in PAIR_TOPOLOGY_COLUMNS
                for index in range(NUMBER_OF_JETS)
            )
            topology = np.column_stack(topology_values).astype(np.float32, copy=False)
            if file_weights is not None:
                process_name, event_weight = file_weights[path]
                weights = np.full(len(jets), event_weight, dtype=np.float64)
            else:
                process_name = inferred_process_name(path, split_root, class_name)
                weights = (numeric_array(arrays[weight_column]) if use_weight_column
                           else np.ones(len(jets), dtype=np.float32)) * weight_scale
            if maximum > 0:
                remaining = maximum - loaded
                if remaining <= 0:
                    break
                jets, topology, weights = (jets[:remaining], topology[:remaining],
                                           weights[:remaining])
            for names, values in ((jet_features, jets.reshape(-1, len(jet_features))),
                                  (topology_names, topology)):
                for index, name in enumerate(names):
                    missing_counts[name] = missing_counts.get(name, 0) + int(
                        np.isnan(values[:, index]).sum())
                    infinity_counts[name] = infinity_counts.get(name, 0) + int(
                        np.isinf(values[:, index]).sum())
            jets[np.isinf(jets)] = np.nan
            topology[np.isinf(topology)] = np.nan
            if np.any(~np.isfinite(weights)) or np.any(weights < 0):
                raise ValueError(f"{path}: event weights must be finite and non-negative")
            jet_blocks.append(jets.astype(np.float32, copy=False))
            topology_blocks.append(topology)
            weight_blocks.append(weights.astype(np.float64, copy=False))
            process_blocks.append(np.full(len(jets), process_name, dtype=object))
            loaded += len(jets)
            if maximum > 0 and loaded >= maximum:
                break
        print(f"\r  shard {file_number:>4}/{len(files)} | events: {loaded:,}",
              end="", flush=True)
        if maximum > 0 and loaded >= maximum:
            break
    print()
    if not jet_blocks:
        raise ValueError(f"No events loaded for {description}")
    return EventData(
        np.concatenate(jet_blocks), np.concatenate(topology_blocks),
        np.concatenate(weight_blocks), np.concatenate(process_blocks),
        use_weight_column or file_weights is not None,
        {k: v for k, v in missing_counts.items() if v},
        {k: v for k, v in infinity_counts.items() if v},
    )


def event_feature_names() -> list[str]:
    names = ["leading_jet_score", "subleading_jet_score",
             *SCALAR_TOPOLOGY_COLUMNS]
    names.extend(f"{rank}_{name}" for name in PAIR_TOPOLOGY_COLUMNS
                 for rank in ("leading", "subleading"))
    return names


def predict_two_scores(model, jet_inputs: np.ndarray) -> np.ndarray:
    flat = jet_inputs.reshape(-1, jet_inputs.shape[-1])
    return model.predict_proba(flat)[:, 1].reshape(len(jet_inputs), NUMBER_OF_JETS)


def balanced_training_weights(labels: np.ndarray, physical: np.ndarray) -> np.ndarray:
    result = physical.astype(np.float64, copy=True)
    for label in (0, 1):
        mask = labels == label
        total = result[mask].sum()
        if total <= 0:
            raise ValueError(f"Class {label} has zero total training weight")
        result[mask] *= 0.5 / total
    result *= len(result) / result.sum()
    return result


def cross_fitted_scores(jet_inputs: np.ndarray, event_labels: np.ndarray,
                        event_weights: np.ndarray, template_model, folds: int,
                        random_state: int) -> np.ndarray:
    scores = np.full((len(event_labels), NUMBER_OF_JETS), np.nan, dtype=np.float32)
    splitter = StratifiedKFold(n_splits=folds, shuffle=True, random_state=random_state)
    for fold, (fit_indices, score_indices) in enumerate(
            splitter.split(np.zeros(len(event_labels)), event_labels), 1):
        model = clone(template_model)
        jet_x = jet_inputs[fit_indices].reshape(-1, jet_inputs.shape[-1])
        jet_y = np.repeat(event_labels[fit_indices], NUMBER_OF_JETS)
        jet_w = np.repeat(event_weights[fit_indices], NUMBER_OF_JETS)
        jet_w = balanced_training_weights(jet_y, jet_w)
        print(f"\nCross-fit jet tagger {fold}/{folds}: fitting {len(jet_y):,} jets")
        model.fit(jet_x, jet_y, sample_weight=jet_w)
        scores[score_indices] = predict_two_scores(model, jet_inputs[score_indices])
    if np.any(~np.isfinite(scores)):
        raise RuntimeError("Cross-fitting did not produce every training-event score")
    return scores


def combine(signal: EventData, background: EventData, signal_scores: np.ndarray,
            background_scores: np.ndarray, random_state: int):
    x = np.concatenate((np.column_stack((signal_scores, signal.topology)),
                        np.column_stack((background_scores, background.topology))))
    y = np.concatenate((np.ones(len(signal.topology), dtype=np.int8),
                        np.zeros(len(background.topology), dtype=np.int8)))
    w = np.concatenate((signal.weights, background.weights))
    processes = np.concatenate((signal.processes, background.processes))
    rng = np.random.default_rng(random_state)
    order = rng.permutation(len(y))
    return x[order], y[order], w[order], processes[order]


def asimov_significance(signal: float, background: float,
                        fractional_uncertainty: float) -> float:
    if signal <= 0 or background <= 0:
        return 0.0
    if fractional_uncertainty == 0:
        return math.sqrt(max(0.0, 2 * ((signal + background)
                              * math.log1p(signal / background) - signal)))
    sigma2 = (fractional_uncertainty * background) ** 2
    first = (signal + background) * math.log(
        ((signal + background) * (background + sigma2))
        / (background * background + (signal + background) * sigma2)
    )
    second = (background * background / sigma2) * math.log(
        1 + sigma2 * signal / (background * (background + sigma2))
    )
    return math.sqrt(max(0.0, 2 * (first - second)))


def scan_significance(labels: np.ndarray, scores: np.ndarray, weights: np.ndarray,
                      points: int, systematics: list[float],
                      optimize_systematic: float, min_background_neff: float):
    quantiles = np.linspace(0, 1, points)
    # Include both event-count and yield quantiles.  The latter prevents a
    # high-weight, low-statistics process from being skipped by the scan grid.
    thresholds = np.unique(np.concatenate((
        np.quantile(scores, quantiles),
        weighted_quantile(scores, quantiles, weights),
    )))
    rows = []
    total_s = weights[labels == 1].sum()
    total_b = weights[labels == 0].sum()
    for threshold in thresholds:
        accepted = scores >= threshold
        smask = accepted & (labels == 1)
        bmask = accepted & (labels == 0)
        signal = float(weights[smask].sum())
        background = float(weights[bmask].sum())
        sumw2_s = float(np.square(weights[smask]).sum())
        sumw2_b = float(np.square(weights[bmask]).sum())
        neff_s = signal * signal / sumw2_s if sumw2_s > 0 else 0.0
        neff_b = background * background / sumw2_b if sumw2_b > 0 else 0.0
        row = {
            "threshold": float(threshold), "signal_yield": signal,
            "background_yield": background,
            "signal_events": int(smask.sum()),
            "background_events": int(bmask.sum()),
            "signal_efficiency": signal / total_s if total_s else 0.0,
            "background_efficiency": background / total_b if total_b else 0.0,
            "signal_over_background": signal / background if background else math.inf,
            "signal_over_sqrt_background": signal / math.sqrt(background)
            if background else math.inf,
            "signal_neff": neff_s, "background_neff": neff_b,
        }
        for systematic in systematics:
            row[systematic_key(systematic)] = asimov_significance(
                signal, background, systematic
            )
        rows.append(row)
    eligible = [row for row in rows if row["background_neff"] >= min_background_neff]
    if not eligible:
        raise RuntimeError("No threshold satisfies --min-background-neff")
    best = max(eligible, key=lambda row: row[systematic_key(optimize_systematic)])
    return rows, best


def systematic_key(fraction: float) -> str:
    return f"asimov_z_bkg_syst_{100.0 * fraction:g}pct"


def process_composition(labels: np.ndarray, processes: np.ndarray,
                        scores: np.ndarray, weights: np.ndarray,
                        threshold: float) -> list[dict]:
    accepted = scores >= threshold
    rows = []
    for process in sorted(set(processes.tolist())):
        process_mask = processes == process
        class_labels = np.unique(labels[process_mask])
        if len(class_labels) != 1:
            raise ValueError(f"Process {process!r} appears in both classes")
        selected = process_mask & accepted
        total_yield = float(weights[process_mask].sum())
        selected_yield = float(weights[selected].sum())
        sumw2 = float(np.square(weights[selected]).sum())
        rows.append({
            "process": process,
            "class": "signal" if class_labels[0] == 1 else "background",
            "events_total": int(process_mask.sum()),
            "events_selected": int(selected.sum()),
            "yield_total": total_yield,
            "yield_selected": selected_yield,
            "efficiency": selected_yield / total_yield if total_yield else 0.0,
            "sumw2_selected": sumw2,
            "neff_selected": selected_yield ** 2 / sumw2 if sumw2 else 0.0,
        })
    background_yield = sum(row["yield_selected"] for row in rows
                           if row["class"] == "background")
    for row in rows:
        row["selected_background_fraction"] = (
            row["yield_selected"] / background_yield
            if row["class"] == "background" and background_yield else 0.0
        )
    return rows


def weighted_quantile(values: np.ndarray, quantiles: np.ndarray,
                      weights: np.ndarray) -> np.ndarray:
    order = np.argsort(values)
    values, weights = values[order], weights[order]
    cumulative = np.cumsum(weights) - 0.5 * weights
    if cumulative[-1] <= 0:
        return np.quantile(values, quantiles)
    cumulative /= cumulative[-1]
    return np.interp(quantiles, cumulative, values)


def make_templates(labels: np.ndarray, processes: np.ndarray, scores: np.ndarray,
                   weights: np.ndarray,
                   bins: int) -> tuple[np.ndarray, list[dict[str, float | int]]]:
    background = labels == 0
    edges = weighted_quantile(scores[background], np.linspace(0, 1, bins + 1),
                              weights[background])
    edges[0], edges[-1] = 0.0, 1.0
    edges = np.unique(edges)
    if len(edges) < 3:
        edges = np.linspace(0, 1, bins + 1)
    rows = []
    for index in range(len(edges) - 1):
        in_bin = ((scores >= edges[index]) &
                  (scores < edges[index + 1] if index < len(edges) - 2
                   else scores <= edges[index + 1]))
        row: dict[str, float | int] = {"bin": index,
            "low": float(edges[index]), "high": float(edges[index + 1])}
        for label, name in ((1, "signal"), (0, "background")):
            mask = in_bin & (labels == label)
            row[f"{name}_yield"] = float(weights[mask].sum())
            row[f"{name}_sumw2"] = float(np.square(weights[mask]).sum())
            row[f"{name}_events"] = int(mask.sum())
        for process in sorted(set(processes.tolist())):
            mask = in_bin & (processes == process)
            safe_name = "".join(character if character.isalnum() else "_"
                                for character in process).strip("_")
            row[f"process_{safe_name}_yield"] = float(weights[mask].sum())
            row[f"process_{safe_name}_sumw2"] = float(np.square(weights[mask]).sum())
            row[f"process_{safe_name}_events"] = int(mask.sum())
        rows.append(row)
    return edges, rows


def write_csv(path: Path, rows: list[dict]) -> None:
    if not rows:
        return
    import csv
    with path.open("w", newline="") as stream:
        writer = csv.DictWriter(stream, fieldnames=list(rows[0]))
        writer.writeheader()
        writer.writerows(rows)


def plot_outputs(output_dir: Path, labels: np.ndarray, scores: np.ndarray,
                 weights: np.ndarray, scan_rows: list[dict], auc: float,
                 optimize_systematic: float) -> None:
    fpr, tpr, _ = roc_curve(labels, scores, sample_weight=weights)
    fig, ax = plt.subplots(figsize=(7, 6))
    ax.plot(fpr, tpr, lw=2, label=f"Validation ROC (AUC = {auc:.4f})")
    ax.plot([0, 1], [0, 1], "--", color="black", alpha=.5)
    ax.set(xlabel="Background efficiency", ylabel="Signal efficiency",
           title="Two jet scores + event topology BDT")
    ax.grid(alpha=.25); ax.legend(loc="lower right"); fig.tight_layout()
    fig.savefig(output_dir / "validation_roc.png", dpi=200); plt.close(fig)

    fig, ax = plt.subplots(figsize=(7, 6))
    edges = np.linspace(0, 1, 41)
    for label, name, color in ((0, "Background", "tab:blue"),
                               (1, "Signal", "tab:orange")):
        mask = labels == label
        ax.hist(scores[mask], bins=edges, weights=weights[mask], histtype="step",
                linewidth=2, label=name, color=color)
    ax.set_yscale("log"); ax.set(xlabel="Event BDT score",
                                 ylabel="Weighted events (expected yield if normalised)",
                                 title="Validation event-score templates")
    ax.grid(alpha=.2); ax.legend(); fig.tight_layout()
    fig.savefig(output_dir / "weighted_score_distribution.png", dpi=200); plt.close(fig)

    fig, ax = plt.subplots(figsize=(7, 6))
    ax.plot([r["threshold"] for r in scan_rows],
            [r[systematic_key(optimize_systematic)] for r in scan_rows], lw=2)
    ax.set(xlabel="Minimum event BDT score", ylabel=r"Asimov $Z_A$",
           title=("Expected significance versus event-score threshold\n"
                  f"background uncertainty = {100 * optimize_systematic:g}%"))
    ax.grid(alpha=.25); fig.tight_layout()
    fig.savefig(output_dir / "significance_scan.png", dpi=200); plt.close(fig)


def main() -> None:
    args = parse_args()
    validate_args(args)
    bundle = joblib.load(args.jet_model)
    if not isinstance(bundle, dict) or "model" not in bundle or "features" not in bundle:
        raise ValueError("Jet model must be the dictionary bundle from train_per_jet_bdt.py")
    jet_model = bundle["model"]
    jet_features = list(bundle["features"])
    if len(set(jet_features)) != len(jet_features):
        raise ValueError("Jet-model bundle contains duplicate features")

    roots = {
        "signal_train": args.dataset_root / "signal" / "train",
        "background_train": args.dataset_root / "background" / "train",
        "signal_validation": validation_directory(args.dataset_root / "signal"),
        "background_validation": validation_directory(args.dataset_root / "background"),
    }
    files = {name: parquet_files(root) for name, root in roots.items()}
    all_files = [path for paths in files.values() for path in paths]
    manifest_samples: list[SampleNormalization] = []
    luminosity_ab_inv = None
    file_weight_maps: dict[str, dict[Path, tuple[str, float]] | None] = {
        name: None for name in files
    }
    if args.normalization_manifest is not None:
        luminosity_ab_inv, manifest_samples = load_normalization_manifest(
            args.normalization_manifest
        )
        use_weight_column = False
        use_weights = True
        if args.max_validation_events_per_class:
            raise ValueError(
                "Physical validation yields require --max-validation-events-per-class 0"
            )
        if args.max_training_events_per_class:
            warnings.warn(
                "A training cap can alter the physical process mixture. Use 0 for the "
                "final model, or treat this run as a pilot."
            )
        for name, paths in files.items():
            class_name, split = name.split("_", 1)
            file_weight_maps[name] = manifest_file_weights(
                paths, args.dataset_root, class_name, split,
                luminosity_ab_inv, manifest_samples, args.weight_scale,
            )
    else:
        use_weight_column = weight_availability(all_files, args.weight_column)
        use_weights = use_weight_column
    if not use_weights:
        warnings.warn(f"{args.weight_column!r} is absent: using unit weights. "
                      "Significance is an unnormalised proxy, not expected sensitivity.")
    validate_schema(all_files, jet_features, use_weight_column, args.weight_column)
    print("\nEvent-model inputs:")
    for index, name in enumerate(event_feature_names(), 1):
        print(f"  {index:>2}. {name}")

    loaded = {}
    for name in files:
        maximum = (args.max_training_events_per_class if name.endswith("train")
                   else args.max_validation_events_per_class)
        loaded[name] = load_events(files[name], jet_features, args.batch_size,
                                   maximum, name.replace("_", " "), use_weight_column,
                                   args.weight_column, args.weight_scale, roots[name],
                                   name.split("_", 1)[0], file_weight_maps[name])

    train_event_labels = np.concatenate((
        np.ones(len(loaded["signal_train"].topology), dtype=np.int8),
        np.zeros(len(loaded["background_train"].topology), dtype=np.int8)))
    train_event_weights = np.concatenate((loaded["signal_train"].weights,
                                          loaded["background_train"].weights))
    train_jets = np.concatenate((loaded["signal_train"].jet_inputs,
                                 loaded["background_train"].jet_inputs))
    if args.training_score_mode == "crossfit":
        all_train_scores = cross_fitted_scores(
            train_jets, train_event_labels, train_event_weights, jet_model,
            args.cross_fit_folds, args.random_state)
    else:
        warnings.warn("Using in-sample pretrained jet scores; results can be optimistic.")
        all_train_scores = predict_two_scores(jet_model, train_jets)
    n_signal_train = len(loaded["signal_train"].topology)
    signal_train_scores = all_train_scores[:n_signal_train]
    background_train_scores = all_train_scores[n_signal_train:]
    signal_validation_scores = predict_two_scores(
        jet_model, loaded["signal_validation"].jet_inputs)
    background_validation_scores = predict_two_scores(
        jet_model, loaded["background_validation"].jet_inputs)

    x_train, y_train, w_train_physical, train_processes = combine(
        loaded["signal_train"], loaded["background_train"],
        signal_train_scores, background_train_scores, args.random_state)
    x_validation, y_validation, w_validation, validation_processes = combine(
        loaded["signal_validation"], loaded["background_validation"],
        signal_validation_scores, background_validation_scores, args.random_state + 1)
    training_weights = balanced_training_weights(y_train, w_train_physical)
    model = HistGradientBoostingClassifier(
        loss="log_loss", learning_rate=args.learning_rate,
        max_iter=args.max_iterations, max_leaf_nodes=args.max_leaf_nodes,
        min_samples_leaf=args.min_samples_leaf,
        l2_regularization=args.l2_regularization, early_stopping=True,
        validation_fraction=.1, n_iter_no_change=20, scoring="roc_auc",
        random_state=args.random_state, verbose=1)
    print(f"\nTraining event BDT on {len(y_train):,} events")
    model.fit(x_train, y_train, sample_weight=training_weights)
    scores = model.predict_proba(x_validation)[:, 1]
    auc = float(roc_auc_score(y_validation, scores, sample_weight=w_validation))
    ap = float(average_precision_score(y_validation, scores, sample_weight=w_validation))
    scan_rows, best = scan_significance(
        y_validation, scores, w_validation, args.scan_points,
        args.background_systematics, args.optimize_background_systematic,
        args.min_background_neff)
    composition_rows = process_composition(
        y_validation, validation_processes, scores, w_validation,
        best["threshold"])
    edges, template_rows = make_templates(
        y_validation, validation_processes, scores, w_validation,
        args.template_bins)

    args.output_dir.mkdir(parents=True, exist_ok=True)
    joblib.dump({"model": model, "features": event_feature_names(),
                 "jet_model": str(args.jet_model),
                 "jet_features": jet_features,
                 "training_score_mode": args.training_score_mode,
                 "best_validation_threshold": best["threshold"],
                 "optimization_background_systematic":
                     args.optimize_background_systematic,
                 "normalization_manifest": (str(args.normalization_manifest)
                                              if args.normalization_manifest else None)},
                args.output_dir / "event_bdt.joblib")
    write_csv(args.output_dir / "significance_scan.csv", scan_rows)
    write_csv(args.output_dir / "fit_templates.csv", template_rows)
    write_csv(args.output_dir / "best_cut_process_composition.csv", composition_rows)
    plot_outputs(args.output_dir, y_validation, scores, w_validation,
                 scan_rows, auc, args.optimize_background_systematic)

    importance_summary = None
    if args.importance_events > 0:
        rng = np.random.default_rng(args.random_state)
        count = min(args.importance_events, len(y_validation))
        indices = rng.choice(len(y_validation), count, replace=False)
        importance = permutation_importance(
            model, x_validation[indices], y_validation[indices],
            sample_weight=w_validation[indices], scoring="roc_auc",
            n_repeats=args.importance_repeats, random_state=args.random_state,
            n_jobs=args.n_jobs)
        importance_summary = {
            name: {"mean_auc_decrease": float(mean), "std": float(std)}
            for name, mean, std in sorted(zip(event_feature_names(),
                                               importance.importances_mean,
                                               importance.importances_std),
                                          key=lambda item: item[1], reverse=True)}
        order = np.argsort(importance.importances_mean)
        fig, ax = plt.subplots(figsize=(9, 7))
        ax.barh(np.asarray(event_feature_names())[order],
                importance.importances_mean[order],
                xerr=importance.importances_std[order], alpha=.8)
        ax.set(xlabel="Decrease in weighted validation ROC AUC after permutation",
               title="Event BDT permutation importance")
        ax.grid(axis="x", alpha=.25); fig.tight_layout()
        fig.savefig(args.output_dir / "permutation_importance.png", dpi=200)
        plt.close(fig)

    metrics = {
        "model": "two jet scores plus event topology HistGradientBoostingClassifier",
        "features": event_feature_names(), "jet_features": jet_features,
        "training_score_mode": args.training_score_mode,
        "cross_fit_folds": args.cross_fit_folds if args.training_score_mode == "crossfit" else None,
        "validation": {"weighted_roc_auc": auc, "weighted_average_precision": ap,
                       "best_cut": best,
                       "optimization_background_systematic_fraction":
                           args.optimize_background_systematic,
                       "reported_background_systematic_fractions":
                           args.background_systematics,
                       "weights_are_physical_expected_yields": use_weights,
                       "template_edges": edges.tolist(),
                       "best_cut_process_composition": composition_rows},
        "counts": {"training_signal_events": n_signal_train,
                   "training_background_events": len(loaded["background_train"].topology),
                   "validation_signal_events": len(loaded["signal_validation"].topology),
                   "validation_background_events": len(loaded["background_validation"].topology)},
        "training": {"iterations_used": int(model.n_iter_),
                     "class_totals_balanced": True,
                     "physical_background_composition_preserved": use_weights},
        "normalization": {
            "source": ("manifest" if args.normalization_manifest else
                       (f"parquet column {args.weight_column}" if use_weight_column
                        else "unit weights")),
            "manifest": (str(args.normalization_manifest)
                         if args.normalization_manifest else None),
            "luminosity_ab_inv": luminosity_ab_inv,
            "weight_scale": args.weight_scale,
            "samples": [sample.__dict__ for sample in manifest_samples],
        },
        "data_quality": {name: {"missing": data.missing,
                                  "infinities_converted_to_nan": data.infinities}
                         for name, data in loaded.items()},
        "permutation_importance": importance_summary,
        "interpretation": ("expected sensitivity" if use_weights
                           else "unnormalised unit-weight sensitivity proxy"),
    }
    (args.output_dir / "metrics.json").write_text(
        json.dumps(metrics, indent=2, allow_nan=True) + "\n")

    print("\nValidation result")
    print(f"  Weighted ROC AUC:          {auc:.6f}")
    print(f"  Weighted average precision:{ap:>10.6f}")
    print(f"  Best threshold:            {best['threshold']:.6f}")
    print(f"  Signal yield:              {best['signal_yield']:.6g}")
    print(f"  Background yield:          {best['background_yield']:.6g}")
    print(f"  Signal efficiency:         {best['signal_efficiency']:.6f}")
    print(f"  Background efficiency:     {best['background_efficiency']:.6e}")
    print(f"  S/B:                       {best['signal_over_background']:.6g}")
    for systematic in args.background_systematics:
        print(f"  Asimov Z ({100 * systematic:g}% bkg syst):"
              f" {best[systematic_key(systematic)]:.6f}")
    print(f"  Background effective N:    {best['background_neff']:.3f}")
    print("\n  Best-cut process composition")
    print("    process                         class          yield      efficiency       Neff")
    for row in composition_rows:
        print(f"    {row['process'][:30]:<30} {row['class']:<10}"
              f" {row['yield_selected']:>12.6g} {row['efficiency']:>14.6e}"
              f" {row['neff_selected']:>10.2f}")
    if not use_weights:
        print("  NOTE: unit weights were used; Z is not a physical expected sensitivity.")
    print(f"\nSaved under {args.output_dir}")


if __name__ == "__main__":
    main()